version: '3.8'

services:
  db:
    image: mysql:8.0.37
    container_name: coachcoach-db
    environment:
      MYSQL_ROOT_PASSWORD: coach1234
      MYSQL_DATABASE: coachcoach
      MYSQL_USER: coachcoach
      MYSQL_PASSWORD: coach1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - coachcoach-network

  flyway:
    image: flyway/flyway:8.0.4
    container_name: coachcoach-flyway
    command: -url=jdbc:mysql://db:3306/coachcoach -user=coachcoach -password=coach1234 -schemas=coachcoach table=flyway_schema_history migrate
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - coachcoach-network

  mongo:
    image: mongo:7.0.5
    container_name: coachcoach-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: coachcoach
      MONGO_INITDB_ROOT_PASSWORD: coach1234
    volumes:
      - mongo_data:/data/db
    networks:
      - coachcoach-network

networks:
  coachcoach-network:

volumes:
  db_data:
  mongo_data:
