version: '3.8'

services:
  db:
    image: mysql:8.0.37
    restart: always
    container_name: coachcoach-db
    environment:
      MYSQL_USER: coachcoach
      MYSQL_PASSWORD: coach1234
      MYSQL_DATABASE: coachcoach
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
