name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: coachcoach-bucket
  CODE_DEPLOY_APPLICATION_NAME: coachcoach_cicd

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # (2) application.properties 설정
      - name: Setup application.properties
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.CI_APPLICATION }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

      # (3) gradlew 권한 추가
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # (4) JDK 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # (5) Gradle test and build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # (6) checkStyle 검사
      - name: Run java checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: ./config/checkstyle/naver-checkstyle-rules.xml
          properties_file: ./config/checkstyle/naver-checkstyle-suppressions.xml
